-- ============================================================
-- DEEPFOG Database Schema
-- Intelligent Mine Vehicle Safety & Low-Visibility Monitoring
-- ============================================================
-- This schema creates the PostgreSQL tables required for DEEPFOG.
--
-- Usage:
--   1. Create the database:  CREATE DATABASE deepfog;
--   2. Connect to it:        \c deepfog
--   3. Run this file:        \i schema.sql
-- ============================================================

-- Enable UUID extension (optional, for future use)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- VEHICLES TABLE
-- Stores registered mine vehicles / HEMMs
-- ============================================================
CREATE TABLE IF NOT EXISTS vehicles (
    id              SERIAL PRIMARY KEY,
    vehicle_id      VARCHAR(50) UNIQUE NOT NULL,       -- e.g. "DEEPFOG-01"
    vehicle_name    VARCHAR(100) NOT NULL,              -- e.g. "Dumper Truck Alpha"
    vehicle_type    VARCHAR(50) DEFAULT 'HEMM',         -- HEMM, Dumper, Excavator, etc.
    status          VARCHAR(20) DEFAULT 'INACTIVE',     -- ACTIVE, INACTIVE, MAINTENANCE
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- SENSOR_READINGS TABLE
-- Stores every sensor payload received from ESP32 devices
-- ============================================================
CREATE TABLE IF NOT EXISTS sensor_readings (
    id              SERIAL PRIMARY KEY,
    vehicle_id      VARCHAR(50) NOT NULL REFERENCES vehicles(vehicle_id),
    latitude        DOUBLE PRECISION,                   -- GPS latitude
    longitude       DOUBLE PRECISION,                   -- GPS longitude
    temperature     REAL,                               -- °C from DHT11
    humidity        REAL,                               -- % from DHT11
    gas_level       REAL,                               -- Analog reading from MQ-2
    light_level     REAL,                               -- Analog reading from LDR
    distance        REAL,                               -- cm from HC-SR04
    acceleration    REAL,                               -- g-force from MPU6050
    tilt            REAL,                               -- degrees from MPU6050
    vibration       BOOLEAN DEFAULT FALSE,              -- SW-420 triggered
    risk_level      VARCHAR(10) DEFAULT 'LOW',          -- LOW, MEDIUM, HIGH
    risk_score      INTEGER DEFAULT 0,                  -- 0-100 calculated score
    risk_reasons    TEXT[] DEFAULT '{}',                 -- Array of risk reason strings
    recorded_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- ALERTS TABLE
-- Stores alert events generated by risk calculations
-- ============================================================
CREATE TABLE IF NOT EXISTS alerts (
    id              SERIAL PRIMARY KEY,
    vehicle_id      VARCHAR(50) NOT NULL REFERENCES vehicles(vehicle_id),
    alert_type      VARCHAR(50) NOT NULL,               -- VISIBILITY, GAS, VIBRATION, etc.
    severity        VARCHAR(10) NOT NULL DEFAULT 'LOW',  -- LOW, MEDIUM, HIGH
    message         TEXT NOT NULL,                       -- Human-readable alert message
    risk_score      INTEGER DEFAULT 0,                  -- Risk score at time of alert
    status          VARCHAR(20) DEFAULT 'ACTIVE',       -- ACTIVE, ACKNOWLEDGED, RESOLVED
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at     TIMESTAMP
);

-- ============================================================
-- INDEXES for query performance
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_sensor_vehicle_id ON sensor_readings(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_sensor_recorded_at ON sensor_readings(recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_sensor_vehicle_time ON sensor_readings(vehicle_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_vehicle_id ON alerts(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status);
CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts(created_at DESC);

-- ============================================================
-- INSERT DEFAULT VEHICLE (for development / demo)
-- ============================================================
INSERT INTO vehicles (vehicle_id, vehicle_name, vehicle_type, status)
VALUES ('DEEPFOG-01', 'Dumper Truck Alpha', 'HEMM', 'ACTIVE')
ON CONFLICT (vehicle_id) DO NOTHING;

-- ============================================================
-- FUNCTION: Update the updated_at timestamp automatically
-- ============================================================
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for vehicles table
DROP TRIGGER IF EXISTS set_vehicle_updated_at ON vehicles;
CREATE TRIGGER set_vehicle_updated_at
    BEFORE UPDATE ON vehicles
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();
